### ISSUE TITLE
channels.json empty/null

### ISSUE THREAD

**Issue by csaket** [rusq/slackdump#110]
**Describe the bug**
When running slackdump, channels.json has `null` as the only content.
This results in the export not being usable with a viewer.

**To Reproduce**
1. Run slackdump like this './slackdump -v -export bug -download' with 1 or more channels ids.

**Expected behavior**
Correct channels.json generation.

**Desktop (please complete the following information):**
 - OS: Windows 11 insider/wsl2/Ubuntu 22.04/slackdump 2.1.1
 
Windows version 2.0.3 also resulted in the same issue.
Just tried with 2.1.2 on windows and it also resulted in the same issue.

**Comment by rusq** [comment]
Intersting, I had never had an emtpy channels output:

1. are you running export on the full account or guest?
2. If you run `./slackdump -c` does it list the channels?

**Comment by csaket** [comment]
Must have been a temporary glitch for our slack account.
I am able to get the data correctly now.

**Comment by rusq** [comment]
@csaket I found out what's causing it, because stumbled on my own.

When running the export for only DMs, the `channels.json`, which lists the public channels contains just `null`, because there are no public channels requested.

I just submitted the #160 , it fixes this behaviour by initialising channels with empty list.  This will prevent slack-export-viewer from crashing in surprise.
