### ISSUE TITLE
Error net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes

### ISSUE THREAD

**Issue by yoshimotomasahir** [rusq/slackdump#175]
I encountered the error messages in Windows version.

> Slackdump v2.2.5 Copyright (c) 2018-2022 rusq (build: 2ce8ba0)
> 
> ? What would you like to do? Export
> ? Output directory or ZIP file:  [? for help] ZIP
> 
> ? Output directory or ZIP file:  ZIP
> ? Conversations to export (leave empty for ALL):  [? for help] ALL
> 
> ? Conversations to export (leave empty for ALL):  ALL
> ? Export files? Yes
> ? Export type:  Standard
> ? Append export token (leave empty if none) [? for help]
> 
> ? Append export token (leave empty if none)
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 > checking user cache...
> 2022/12/26 17:14:23 Export:  staring export to: <directory: ZIP>
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
> 2022/12/26 17:14:23 application error: export error: error getting info for ALL: channel_not_found

I think it is not a slackdump error. 
However, if there is a solution please let me know.

**Comment by rusq** [comment]
Hi @yoshimotomasahir, thanks for the report.  I think I seen it before, and it was the reason for #158 - some of those thirdparty cookies upset net/http package.  But then #168 happened, and I rolled it back.  The problem was that there were some oauth cookies set by Google that got cleaned up by slackdump's cookie filter introduced in #158, which prevented Google Auth from logging in.

However, I don't think that's the issue here, when I experiemented with them, these particular log errors do not prevent slack from working.

I think it is not clearly documented that if you want ALL channels to be exported, you need to just press return in response to this question
> ? Conversations to export (leave empty for ALL): [? for help]

**Comment by yoshimotomasahir** [comment]
@rusq 
It seems I forgot a little bit how to use this useful tool.
Entering "empty" gave the desired result to me.

Thank you very much.

**Comment by rusq** [comment]
That's no problem :) Glad it worked!
