### ISSUE TITLE
failed to initialise the auth provider

### ISSUE THREAD

**Issue by kavol** [rusq/slackdump#251]
**Describe the bug**
After providing the workspace name, opening the browser and logging in, the browser stays open and I get an error after a few minutes.

**To Reproduce**
1. ./slackdump -download -export dump id

**Expected behavior**
conversation exported into dump

**Output**
Slackdump dev (commit: placeholder) built on: 2077
? Enter Slack Workspace Name:  ourworkspacename
Please login in the browser...
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
2023/12/21 15:43:14 failed to initialise the auth provider: Timeout 300000.00ms exceeded.

**Desktop (please complete the following information):**
 - OS: Fedora 39

**Additional context**
It worked until some web layout change (adding a sidebar).

**Comment by rusq** [comment]
Hey @kavol, 

I can see the playwright (that slackdump uses to login) is complaining about the OS, it may be too new for it, and this is what might be causing it. Were you ever able to use slackdump since you upgraded to Fedora 39?

have you tried with an alternative browser?

For example:
```
./slackdump -download -browser chromium -export dump id
```
The command above will use chromium instead of Firefox.

**Comment by rusq** [comment]
Hey, can you also try the v2.4.7?  It has the updated browser driver.

**Comment by kavol** [comment]
> I can see the playwright (that slackdump uses to login) is complaining about the OS, it may be too new for it, and this is what might be causing it. Were you ever able to use slackdump since you upgraded to Fedora 39?

well, yes, I've upgraded on 2023-10-09 and my dumps seem to have stopped working after 2023-11-10 ... this is a month, and since Slack needs relogin every two weeks (which I'm constantly forgetting about :-( ) I must have logged in succesfully on F39 at least once

> have you tried with an alternative browser?
> 
> For example:
> 
> ```
> ./slackdump -download -browser chromium -export dump id
> ```

the thing is that it starts Firefox in this case too ... looks like another issue

> Hey, can you also try the v2.4.7? It has the updated browser driver.

I've pulled from git, ran make, now I can try -browser-reinstall which downloads chromium if specified, but still it runs Firefox instead

**Comment by rusq** [comment]
Does it still print this message?
```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
```
I'm wondering if that's the fallback behaviour, because it works for me

As you seem to have the dev environment correctly setup, to help me diagnose this, could you do the following?

In the local clone of the slackdump repo, run the following:
1. Checkout the i251-take2 branch: `git fetch && git checkout i251-take2`
2. Run auth-reset: `go run ./cmd/slackdump -auth-reset`
3. Run the following command: `go run ./cmd/slackdump -w <your workspace name> -list-users -browser-reinstall -browser chromium -v`

**Comment by kavol** [comment]
bad luck ... but now it opens Chromium at least

```
$ go run ./cmd/slackdump -w workspace -list-users -browser-reinstall -browser chromium -v
Slackdump dev (commit: placeholder) built on: 2077
2024/01/02 13:19:05 Reinstalling chromium
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
2024/01/02 13:19:52 client.go:122: opening browser URL=https://workspace.slack.com
2024/01/02 13:25:01 failed to initialise the auth provider: timeout:Timeout 300000.00ms exceeded.
exit status 1
```

**Comment by kavol** [comment]
oh, right after copying the output, I have noticed that the checkout went wrong

`error: pathspec 'i251-take2' did not match any file(s) known to git`

**Comment by kavol** [comment]
well ... after updating to latest master, it works for me again ... I guess this could be closed then?

**Comment by rusq** [comment]
Yes, I merged i251-take2 into master.  Thanks for the feedback on master, I was actually wondering if it works on other machines, but mine - replaced playwright with rod library.
