### ISSUE TITLE
Add support for dumping an entire workspace

### ISSUE THREAD

**Issue by KingSupernova31** [rusq/slackdump#317]
If I'm understanding this correctly, the only way for me to save the data from several channels is to provide a list of their URLs. I'm just trying to archive everything so it doesn't get lost, so it would be nice to simply be able to download the entire workspace, including all channels that I have access to and all of my DMs with individual members.

**Comment by rusq** [comment]
That is not correct, @KingSupernova31 , see https://github.com/rusq/slackdump/blob/v2/doc/usage-export.rst

**Comment by KingSupernova31** [comment]
Thanks. I'm a bit confused then as to the difference between "dump" and "export". I thought "dump" was for normal JSON output, and "export" was some speciality format for transferring into another program. Is that not the case?

**Comment by rusq** [comment]
"Dump" can be seen as a "raw API output".
The ZIP file (or directory) generated by "Export" is compatible with ZIP files one can get from running Slack Export Workspace as described in [this Slack article](https://slack.com/intl/en-au/help/articles/201658943-Export-your-workspace-data).

Historically (if you look at slackdump prior to version 2, i.e. v1.3.5), there was only "dump" which is the simplest.
To generate an archive in Export format there is some additional logic on top to make it compatible so that one can create an export and import it to, say, another slack instance
