### ISSUE TITLE
Archived channels: fix export and view (master)

### ISSUE THREAD

**Issue by Dmalikhammer4** [rusq/slackdump#324]
Archived threads, even when unarchived lose all their messages, although they are available in the search bar on slack.com, but not anywhere else I don't think? I'm wondering if there is currently functionality to retrieve archived messages/data.

**Comment by rusq** [comment]
That's an interesting question, can you archive threads?  I thought one could archive channels/conversations only.

**Comment by Dmalikhammer4** [comment]
I meant archived channels/conversations, sorry.

**Comment by rusq** [comment]
Hey, I just checked on master branch (v3) - archived channels are being "archived" (select "Archive" mode in wizard) properly, so all data will be retained in the slackdump archive.  Export mode will fail, due to archived channels being "special" - they lack channel users. When slackdump tries to process the archived message (convert it to export format), it panics on master for now.  I will address that when I'll come around to it.

**Comment by rusq** [comment]
This is now fixed!  @Dmalikhammer4 thank you for the report :)
